CREATE PROCEDURE  `SP_STATS_GAME_CONT_3ROUND_MIN_STROKE_SCORE`(
IN $GM_CODE CHAR(13)
)
BEGIN

    DECLARE $MIN_STROKE  INT;
    DECLARE $MIN_STROKE1  INT;
    DECLARE $MIN_STROKE2  INT;
    DECLARE $MAX_RNDG INT;

    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    DROP TEMPORARY TABLE IF EXISTS _TMP;
    CREATE TEMPORARY TABLE IF NOT EXISTS _TMP (
    	SUM_STROKE INT DEFAULT '0' COMMENT '타수 집계',
    	MM_CODE VARCHAR(8) COMMENT '회원코드',
    	MM_NAME_DISPLAY VARCHAR(60) COMMENT '이름',
    	E_MM_NAME_DISPLAY VARCHAR(60) COMMENT '영문이름'
    ) COMMENT='최저타 집계 임시 테이블';

    DROP TEMPORARY TABLE IF EXISTS _TMP1;
    CREATE TEMPORARY TABLE IF NOT EXISTS _TMP1 (
    	SUM_STROKE INT DEFAULT '0' COMMENT '타수 집계',
    	MM_CODE VARCHAR(8) COMMENT '회원코드',
    	MM_NAME_DISPLAY VARCHAR(60) COMMENT '이름',
    	E_MM_NAME_DISPLAY VARCHAR(60) COMMENT '영문이름'
    ) COMMENT='1~2R 최저타 집계 임시 테이블';

    DROP TEMPORARY TABLE IF EXISTS _TMP2;
    CREATE TEMPORARY TABLE IF NOT EXISTS _TMP2 (
    	SUM_STROKE INT DEFAULT '0' COMMENT '타수 집계',
    	MM_CODE VARCHAR(8) COMMENT '회원코드',
    	MM_NAME_DISPLAY VARCHAR(60) COMMENT '이름',
    	E_MM_NAME_DISPLAY VARCHAR(60) COMMENT '영문이름'
    ) COMMENT='2~3R 최저타 집계 임시 테이블';

    SELECT MAX(TOMT_RNDG) INTO $MAX_RNDG
    FROM VW_STATS_SCORE_COMMON
    WHERE GM_CODE = $GM_CODE;

    INSERT INTO _TMP1
    SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18), MAN_CD, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
    FROM VW_STATS_SCORE_COMMON
    WHERE GM_CODE = $GM_CODE
    AND TOMT_RNDG = "1";

    UPDATE _TMP1 A, (
      SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18) AS SUM_STROKE, MAN_CD
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE
      AND TOMT_RNDG = "2" ) B
    SET A.SUM_STROKE = A.SUM_STROKE + B.SUM_STROKE
    WHERE A.MM_CODE = B.MAN_CD;

    UPDATE _TMP1 A, (
      SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18) AS SUM_STROKE, MAN_CD
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE
      AND TOMT_RNDG = "3" ) B
    SET A.SUM_STROKE = A.SUM_STROKE + B.SUM_STROKE
    WHERE A.MM_CODE = B.MAN_CD;

    DELETE FROM _TMP1
    WHERE MM_CODE NOT IN (
        SELECT MAN_CD FROM VW_STATS_SCORE_COMMON WHERE GM_CODE = $GM_CODE AND TOMT_RNDG = $MAX_RNDG
    );

    INSERT INTO _TMP2
    SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18), MAN_CD, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
    FROM VW_STATS_SCORE_COMMON
    WHERE GM_CODE = $GM_CODE
    AND TOMT_RNDG = "2";

    UPDATE _TMP2 A, (
      SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18) AS SUM_STROKE, MAN_CD
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE
      AND TOMT_RNDG = "3" ) B
    SET A.SUM_STROKE = A.SUM_STROKE + B.SUM_STROKE
    WHERE A.MM_CODE = B.MAN_CD;

    UPDATE _TMP2 A, (
      SELECT (H01+H02+H03+H04+H05+H06+H07+H08+H09+H10+H11+H12+H13+H14+H15+H16+H17+H18) AS SUM_STROKE, MAN_CD
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE
      AND TOMT_RNDG = "4" ) B
    SET A.SUM_STROKE = A.SUM_STROKE + B.SUM_STROKE
    WHERE A.MM_CODE = B.MAN_CD;

    DELETE FROM _TMP2
    WHERE MM_CODE NOT IN (
        SELECT MAN_CD FROM VW_STATS_SCORE_COMMON WHERE GM_CODE = $GM_CODE AND TOMT_RNDG = $MAX_RNDG
    );

    SELECT MIN(SUM_STROKE) INTO $MIN_STROKE1 FROM _TMP1 WHERE SUM_STROKE > 0;
    SELECT MIN(SUM_STROKE) INTO $MIN_STROKE2 FROM _TMP2 WHERE SUM_STROKE > 0;

    INSERT INTO _TMP
    SELECT SUM_STROKE, MM_CODE, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
    FROM _TMP1 WHERE SUM_STROKE = $MIN_STROKE1;

    INSERT INTO _TMP
    SELECT SUM_STROKE, MM_CODE, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
    FROM _TMP2 WHERE SUM_STROKE = $MIN_STROKE2;

    SELECT MIN(SUM_STROKE) INTO $MIN_STROKE FROM _TMP WHERE SUM_STROKE > 0;

    SELECT (SUM_STROKE) AS MIN_STROKE, MM_CODE, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
    FROM _TMP WHERE SUM_STROKE = $MIN_STROKE
    GROUP BY MM_CODE;

END;
