CREATE PROCEDURE  `SP_STATS_GAME_SINGLE_SCORE`(
IN $GM_CODE CHAR(13)
)
BEGIN
    SET @SQL_QUERY := CONCAT('SELECT
            (SELECT AVG(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "01") AS AVG_STROKE,
            (SELECT AVG(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "12") AS AVG_BIRDIE,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "17") AS SUM_HOLE_IN_ONE,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "18") AS SUM_ALBATROSS,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "04") AS SUM_EAGLE,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "05") AS SUM_BIRDIE,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "06") AS SUM_PAR,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "19") AS SUM_BOGEY,
            (SELECT SUM(RG_POINT) FROM DR_RCOD_GAME WHERE RG_CODE = "',$GM_CODE,'" AND RG_DIV = "20") AS SUM_DBOGEY');

    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    IF (@SQL_QUERY IS NOT NULL) THEN
        PREPARE $QUERY FROM @SQL_QUERY;
        EXECUTE $QUERY;
        DEALLOCATE PREPARE $QUERY;
    END IF;
END;
