CREATE PROCEDURE  `SP_STATS_GAME_PLAYER`(
IN $MM_CODE VARCHAR(10)
)
BEGIN

    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    SELECT
      B.MM_CODE AS MM_CODE,B.MM_NAME_DISPLAY AS MM_NAME_DISPLAY,
      CONCAT(B.MM_MNAME,' ',B.MM_LNAME,' ',B.MM_FNAME) AS E_MM_NAME_DISPLAY,
      B.MM_NAT, C.NM_ENAME
    FROM CS_MEMB_MST B, SC_NATL_MST C
    WHERE B.MM_NAT = C.NM_CODE;

END;
