CREATE PROCEDURE  `SP_STATS_GAME_MIN72_UNDER_PAR_SCORE`(
IN $GM_CODE CHAR(13),
IN $MODE VARCHAR(20)
)
BEGIN

  IF $MODE is NULL THEN
    SELECT MM_CODE, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY, CNT AS MIN_STROKE
    FROM STATS_SCORE_RANK
    WHERE GM_CODE = $GM_CODE
    AND STATS_DIV = '72HOLE_MIN_UNDER_PAR';
  ELSEIF $MODE = 'GEN' THEN
    BEGIN

      DECLARE $MIN_STROKE INT;
      DECLARE $MAX_RNDG INT;

      SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

      DROP TEMPORARY TABLE IF EXISTS _TMP;
      CREATE TEMPORARY TABLE IF NOT EXISTS _TMP (
      	SUM_STROKE INT DEFAULT '0' COMMENT '타수 집계',
      	MM_CODE VARCHAR(8) COMMENT '회원코드',
      	MM_NAME_DISPLAY VARCHAR(60) COMMENT '이름',
      	E_MM_NAME_DISPLAY VARCHAR(60) COMMENT '영문이름'
      ) COMMENT='최저타 집계 임시 테이블';

      SELECT MAX(TOMT_RNDG) INTO $MAX_RNDG
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE;

      INSERT INTO _TMP
      SELECT ACCU_UNDER, MAN_CD, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY
      FROM VW_STATS_SCORE_COMMON
      WHERE GM_CODE = $GM_CODE
      AND TOMT_RNDG = $MAX_RNDG;

      SELECT MIN(SUM_STROKE) INTO $MIN_STROKE FROM _TMP;

      DELETE FROM STATS_SCORE_RANK
      WHERE GM_CODE = $GM_CODE
      AND STATS_DIV = '72HOLE_MIN_UNDER_PAR';

      INSERT INTO STATS_SCORE_RANK (GM_CODE, MM_CODE, STATS_DIV, MM_NAME_DISPLAY, E_MM_NAME_DISPLAY, CNT)
      SELECT $GM_CODE, MM_CODE, '72HOLE_MIN_UNDER_PAR',MM_NAME_DISPLAY, E_MM_NAME_DISPLAY, SUM_STROKE
      FROM _TMP WHERE SUM_STROKE = $MIN_STROKE
      GROUP BY MM_CODE;

    END;
  END IF;

END;
