CREATE PROCEDURE  `SP_STATS_GAME_SCORE_RANK_TOTAL`()
BEGIN

  DECLARE $MIN_YEAR INT;
  DECLARE $MAX_YEAR INT;

  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

  SELECT MIN(SUBSTRING(GM_CODE,1,4)), MAX(SUBSTRING(GM_CODE,1,4))
  INTO $MIN_YEAR, $MAX_YEAR
  FROM VW_STATS_SCORE_COMMON;

  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

  SET @YEAR := $MAX_YEAR;
  this_loop: LOOP
    IF @YEAR < $MIN_YEAR THEN
      LEAVE this_loop;
    END IF;
    CALL SP_STATS_GAME_SCORE_RANK_YEAR(@YEAR);
    SET @YEAR := @YEAR - 1;
  END LOOP;

END;
