CREATE PROCEDURE  `SP_STATS_GAME_SCORE_RANK`(
IN $GM_CODE CHAR(13)
)
BEGIN

  DECLARE $MODE VARCHAR(20) DEFAULT 'GEN';

  CALL SP_STATS_GAME_CONT_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN09_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN18_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN36_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN54_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN72_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_MIN72_UNDER_PAR_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_CONT_2ROUND_MIN_STROKE_SCORE($GM_CODE,$MODE);
  CALL SP_STATS_GAME_CONT_3ROUND_MIN_STROKE_SCORE($GM_CODE,$MODE);

END;
