CREATE PROCEDURE  `SP_STATS_GAME_LIST`(
IN $YEAR CHAR(4),
IN $TOUR_CODE CHAR(2)
)
BEGIN
    SET @SQL_QUERY := CONCAT('SELECT GM_CODE, GM_NAME
            FROM CG_GAME_MST
            WHERE SUBSTRING(GM_CODE,1,4) = "',$YEAR,'"
            AND GM_TCODE = "',$TOUR_CODE,'"
            AND GM_MONEY <> 0
            AND GM_MENT <> "99"
            AND GM_RULE = "1"
            ORDER BY GM_SDATE');

    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

    IF (@SQL_QUERY IS NOT NULL) THEN
        PREPARE $QUERY FROM @SQL_QUERY;
        EXECUTE $QUERY;
        DEALLOCATE PREPARE $QUERY;
    END IF;
END;
