CREATE TABLE STATS_CODE (
  TBL_GROUP VARCHAR(40) NOT NULL COMMENT '테이블그룹',
  CODE_ID VARCHAR(30) NOT NULL COMMENT '코드아이디',
  CODE_NAME VARCHAR(100) NOT NULL DEFAULT '' COMMENT '코드이름',
  CODE_VALUE VARCHAR(100) DEFAULT NULL COMMENT '코드값',
  PRIMARY KEY (CODE_ID,TBL_GROUP)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COMMENT='통계공통코드';

DELETE FROM STATS_CODE;

INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '01', 'RG_DIV', '평균타수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '02', 'RG_DIV', '그린적중율');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '03', 'RG_DIV', '평균퍼팅수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '04', 'RG_DIV', '이글(누계)');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '05', 'RG_DIV', '버디(누계)');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '06', 'RG_DIV', '파(누계)');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '08', 'RG_DIV', '파세이브');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '09', 'RG_DIV', '파브레이크');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '10', 'RG_DIV', '퍼팅평균(?)');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '11', 'RG_DIV', '총퍼팅수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '12', 'RG_DIV', '평균버디수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '13', 'RG_DIV', '평균이글수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '14', 'RG_DIV', '평균드라이브 비거리');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '15', 'RG_DIV', '페어웨이 안착율');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '16', 'RG_DIV', '벙커세이브(벙커탈출율)');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '17', 'RG_DIV', '홀인원');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '18', 'RG_DIV', '알바트로스');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '19', 'RG_DIV', '보기');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '20', 'RG_DIV', '더블보기');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '21', 'RG_DIV', '트리플보기');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '22', 'RG_DIV', '기타보기');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '31', 'RG_DIV', '라운드평균타수1R');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '32', 'RG_DIV', '라운드평균타수2R');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '33', 'RG_DIV', '라운드평균타수3R');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '34', 'RG_DIV', '라운드평균타수4R');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '35', 'RG_DIV', '라운드평균타수1,2R');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '41', 'RG_DIV', '기준타평균타수 파3');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '42', 'RG_DIV', '기준타평균타수 파4');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '43', 'RG_DIV', '기준타평균타수 파5');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '44', 'RG_DIV', '기준타평균타수 파6');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '51', 'RG_DIV', '기준타버디평균율 파3');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '52', 'RG_DIV', '기준타버디평균율 파4');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '53', 'RG_DIV', '기준타버디평균율 파5');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '54', 'RG_DIV', '기준타버디평균율 파6');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '55', 'RG_DIV', '기준타버디평균율 TOT');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '61', 'RG_DIV', 'T10 피니시'); -- T10
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '62', 'RG_DIV', '파5 세컨샷 그린적중율');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '63', 'RG_DIV', '리커버리율'); -- TSCRAM
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '66', 'RG_DIV', '컷통과횟수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '81', 'RG_DIV', '드라이빙 지수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '82', 'RG_DIV', '아이언샷 지수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '83', 'RG_DIV', '히팅 지수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '84', 'RG_DIV', '종합 지수');
INSERT INTO STATS_CODE (TBL_GROUP, CODE_ID, CODE_NAME, CODE_VALUE) VALUES ( 'DR_RCOD_GAME', '99', 'RG_DIV', '골든스타 포인트');

INSERT INTO STATS_CODE (TBL_GROUP, CODE_NAME, CODE_ID, CODE_VALUE)
SELECT 'DR_RCOD_YEAR', CODE_NAME, CODE_ID, CODE_VALUE
FROM STATS_CODE WHERE TBL_GROUP='DR_RCOD_GAME';

INSERT INTO STATS_CODE (TBL_GROUP, CODE_NAME, CODE_ID, CODE_VALUE)
SELECT 'DR_RCOD_YEAR_BF', CODE_NAME, CODE_ID, CODE_VALUE
FROM STATS_CODE WHERE TBL_GROUP='DR_RCOD_GAME';

SELECT TBL_GROUP, CODE_NAME, CODE_ID, CODE_VALUE
FROM STATS_CODE
WHERE TBL_GROUP = 'DR_RCOD_YEAR'
ORDER BY CODE_ID ASC;



-- SP_STATS_GAME_BP
-- CG_GAME_MST, TB_STA_GAME, CS_MEMB_MST


-- SP_STATS_BP_AVG
-- CG_GAME_MST, TB_STA_GAME,

-- SP_STATS_GAME_MONEY
-- CG_GAME_MST, CG_PLAYER_PRIZ, CS_MEMB_MST, CG_JOIN_PLYR_LST


-- SP_STATS_GAME_MONEY
-- CG_GAME_MST, CG_PLAYER_PRIZ, CG_GAME_MST, CS_MEMB_MST, CG_JOIN_PLYR_LST

-- VW_STATS_LEADERS_PRIZE
-- CG_PRIZ_RANK, CS_MEMB_MST, CG_PRIZ_RANK_GMCNT

-- VW_STATS_LEADERS_POINT
-- CG_PLTR_POINT, CS_MEMB_MST, CG_PRIZ_RANK_GMCNT

-- VW_STATS_LEADERS_COMMON
-- DR_RCOD_YEAR, CS_MEMB_MST, CG_PRIZ_RANK_GMCNT

-- 비회원 상금랭킹
-- CG_PRIZ_RANK, CS_MEMB_MST, CG_PRIZ_RANK_GMCNT

-- 비공식 대회 참석자 상금내역
-- CS_MEMB_MST, CG_GAME_MST, CG_PLYR_DTL, CG_PLAYER_PRIZ

-- Overview, 제네시스 포인트, 제네시스 상금, 신인왕 포인트, 골든스타 포인트,
-- 평균타수, 드라이브 거리, 페어웨이 안착율, 그린적정율, 평균 퍼트수, 톱10 피니시
-- 비회원 상금순위, 비공식대회 상금순위, 드라이브 거리, 페어웨이 안착율
-- 그린적중율, 리커버리율 , 평균퍼팅
-- SP_STATS_LEADERS
-- CG_PRIZ_RANK, CS_MEMB_MST, CG_PRIZ_RANK_GMCNT, CG_PLTR_POINT, DR_RCOD_YEAR, CG_PLAYER_PRIZ

-- SP_STATS_LEADERS_MONEY
-- CG_PRIZ_RANK, DR_RCOD_YEAR, DR_RCOD_YEAR_BF

-- --------------------------------------
-- 스코어링
-- --------------------------------------
-- 평균타수
-- 평균버디수
-- 홀인원수
-- 알바트로스 수
-- 이글 수
-- 버디 수
-- 파 수
-- 보기 수
-- 더블보기 수
-- 연속 버디수
-- 연속 파수
-- 연속 노보기수
-- 9홀 최저타수
-- 18홀 최저타수
-- 36홀 최저타수
-- 54홀 최저타수
-- 72홀 최저타수
-- 72홀 최저언더파
-- 연속 2개 라운드 최저타수
-- 연속 3개 라운드 최저타수
-- 역대 컷오프 최저타수
-- --------------------------------------
