CREATE TABLE STATS_SCORE_RANK (
  GM_CODE CHAR(13) NOT NULL COMMENT '대회코드',
  MM_CODE VARCHAR(8) NOT NULL COMMENT '회원코드',
  TOMT_RNDG INT DEFAULT '0' COMMENT '라운드번호',
  MM_NAME_DISPLAY VARCHAR(60) COMMENT '이름',
  E_MM_NAME_DISPLAY VARCHAR(60) COMMENT '영문이름',
  STATS_DIV  VARCHAR(30) NOT NULL COMMENT '통계항목(연속홀,연속타수)',
  CNT INT NOT NULL DEFAULT '0' COMMENT '횟수',
  UPD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '등록/수정시간',
  PRIMARY KEY (GM_CODE,MM_CODE,TOMT_RNDG,STATS_DIV)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 ROW_FORMAT=COMPACT COMMENT='통계 스코어링 요약 테이블(데이터자동생성)';

DELETE FROM STATS_SCORE_RANK
WHERE GM_CODE = $GM_CODE
AND DIV='CONT_BIRDIE';

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', 'CONT_BIRDIE', '주흥철 3홀, 최이삭 3홀, 김태훈 3홀, 박홍주 3홀, 김도훈 753 3홀, 박준섭 3홀, 전가람 3홀, 김철승 3홀, ');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', 'CONT_PAR', '현정협 14홀, 조민근 14홀, ');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', 'CONT_NOBOGEY', '현정협 18홀, 박홍주 18홀, 강재규 18홀, 맹동섭 18홀, 유송규 18홀, ');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '9HOLE_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '18HOLE_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '36HOLE_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '54HOLE_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '72HOLE_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', '72HOLE_MIN_UNDERPAR', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', 'CONT_2ROUND_MIN_STROKE', '');

INSERT INTO STATS_SCORE_RANK (GM_CODE, GM_DIV, CONTENT)
VALUES ('2016110081000', 'CONT_3ROUND_MIN_STROKE', '');
