-- 역대 대회 목록 구하기
SELECT DISTINCT(GM_CODE) AS GAME_CODE
FROM CG_GAME_MST
WHERE GM_TCODE = $TOUR_CODE
AND GM_CLASS = 'main'
AND GM_SCODE = SUBSTRING($GM_CODE,7,4)
GROUP BY GM_CODE, GM_SCODE
ORDER BY GM_CODE DESC;
