SELECT
RANK() OVER (ORDER BY CAST(PP_RANK AS INT), CAST(PC_GMCNT AS INT),MM_NAME_DISPLAY) AS RANK,
PP_POINT AS POINT,
MM_NAME_DISPLAY,
CONCAT(B.MM_MNAME,' ',B.MM_LNAME,' ',B.MM_FNAME) as E_MM_NAME_DISPLAY,
PC_GMCNT
FROM
CG_PLTR_POINT A INNER JOIN CS_MEMB_MST B ON A.PP_PCODE = B.MM_CODE
LEFT OUTER JOIN CG_PRIZ_RANK_GMCNT C ON A.PP_PCODE = C.PC_PCODE AND A.PP_YEAR = C.PC_YEAR AND A.PP_TCODE = C.PC_TCODE
WHERE 1=1
AND PP_SEASON = IFNULL(PC_SEASON,PP_SEASON)
AND PP_SEASON = (SELECT MAX(PP_SEASON) FROM CG_PLTR_POINT WHERE PP_YEAR = '2016' AND PP_TCODE = '12')
AND PP_YEAR = '2016'
AND PP_TCODE = '12'
AND PP_INDEX = '0'
ORDER BY RANK, PC_GMCNT, MM_NAME_DISPLAY
